### ISSUE TITLE
Implement GET API Endpoint for Leaderboard

### ISSUE THREAD

**Issue by parthgohel1729** [UWL-Software-Engineering/quiz-app-backend#17]
### **Description:**
Create a GET API endpoint to fetch the leaderboard data based on the specified requirements.

### **Acceptance Criteria:**
1. The API endpoint should retrieve the leaderboard data with the following considerations:
   - [ ] Display only participants who have taken a quiz within the last 7 days.
   - [ ] Calculate and display the best quiz score for each participant.
   - [ ] Sort the leaderboard in descending order based on the best quiz scores.
   - [ ] Include participant names and their corresponding best scores in the response.

### **Tasks:**
1. Design the API endpoint URL and request/response structure.
2. Implement backend logic to fetch and process leaderboard data.
3. Apply the 7-day filtering logic to retrieve quiz attempts within the last 7 days.
4. Calculate the best quiz scores for each participant based on the defined rules.
5. Sort the leaderboard data in descending order based on the best quiz scores.
6. Create the API endpoint with appropriate route handling.
7. Ensure error handling for cases where there is no data to display.
8. Write unit tests to verify the correctness of the API endpoint.
   
### **API Endpoint Details:**
- **Endpoint URL:** `/api/leaderboard`
- **Method:** GET
- **Request Parameters:** None
- **Response Format:**
    ```json
    {
      "leaderboard": [
        {
          "participant_name": "John Doe",
          "best_score": 95
        },
        {
          "participant_name": "Jane Smith",
          "best_score": 90
        },
        {
          "participant_name": "Alice Johnson",
          "best_score": 85
        },
        ...
      ]
    }
    ```

**Example Response:**
```json
{
  "leaderboard": [
    {
      "participant_name": "John Doe",
      "best_score": 95
    },
    {
      "participant_name": "Jane Smith",
      "best_score": 90
    },
    {
      "participant_name": "Alice Johnson",
      "best_score": 85
    },
    ...
  ]
}
```

### **Note:**
- The API response should include an array of leaderboard entries, each containing the participant's name and their corresponding best score.
- Ensure the API response is in JSON format and follows the specified structure.
- Handle edge cases such as empty leaderboard (when no participants have taken the quiz in the last 7 days).
